name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" -DBUILD_TESTING="ON" ..
    - name: build
      run: cmake --build build
    - name: test
      run: ./build/test_main
    - name: coverage
      run: |
        sudo apt-get install lcov
        lcov -c -d build/CMakeFiles/scratchy.dir/src/ -o build/coverage.info
        lcov -r build/coverage.info '/usr/*' -o build/coverage.info
        lcov --list build/coverage.info
    - name: upload coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: build/coverage.info
